### ISSUE TITLE
Issue building package

### ISSUE THREAD

**Issue by tOmoness** [conyx/installshield-plugin#1] opened 2014-04-11 09:08 UTC
When Jenkins tries to execute the ISCmdBld executable I get the following error: 'C:\Program' is not recognized as an internal or external command

My path for ISCmdBld.exe is: C:\Program Files (x86)\InstallShield\2012\System\ISCmdBld.exe

**Comment by conyx** [comment] 2014-04-11 10:41
Hi Tom,

could you please provide us the whole Job console output, especially the line starts with "Executing command: ..."

TB

**Comment by tOmoness** [comment] 2014-05-20 14:16
Executing command: "C:\Program Files (x86)\InstallShield\2012\System\ISCmdBld.exe" -p "C:\Jenkins\workspace\InstallShield Projects\Customer Packages\MyProject.ism"  & exit %%ERRORLEVEL%%
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
ISCmdBld.exe ERRORLEVEL code: 9009
Build step 'Execute InstallShield builder' marked build as failure

**Comment by conyx** [comment] 2014-05-20 15:29
Have you tried to paste
"C:\Program Files (x86)\InstallShield\2012\System\ISCmdBld.exe" -p "C:\Jenkins\workspace\InstallShield Projects\Customer Packages\MyProject.ism" & exit %%ERRORLEVEL%%
manually into the Windows command line tool (cmd.exe) and run it? Does it work?

**Comment by tOmoness** [comment] 2014-05-20 15:40
Yeah and it works fine.

**Comment by conyx** [comment] 2014-05-20 16:04
Well, I am not able to reproduce this bug. InstallShield plugin just passes this command into the shell, which is "cmd.exe" in that case, so it should show the same behaviour.
You can try to use a simple batch builder for this purpose although it's not a nice solution.

**Comment by conyx** [comment] 2014-05-22 14:18
Well, I have finally found the bug! The problem is caused by the space sign inside the project file path (...Customer Packages...). New version of IS plugin will be released ASAP!
Thanks for the report. ;)

**Comment by tOmoness** [comment] 2014-05-22 15:00
Fantastic news! I was just using a .bat file for the time being, but well done on finding the issue. I'll update once released. Thanks again.

**Closed as completed** 2014-05-23 08:57 UTC
